language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python main.py
after_script:
  - git init
  - git config user.name "TravisCI"
  - git config user.email "vancirprince@gmail.com"
  - git add -A
  - git commit -m "AutoSync: `date +'%Y-%m-%d %H:%M:%S'`"
  - git push --force --quiet "https://${GOSSIP_TRAVIS_TOKEN}@${GH_REF}" master:master
branches:
  only:
    - master
