name: 'GoSSIP WeChat Official Account AutoSync Bot'

on:
    push:
    schedule:
        - cron: '0 21 * * *'

jobs:
    bot:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: '3.x'
                  architecture: 'x64'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Sync news feed
              run: python main.py