name: sync

on:
  push:
    branches:
      - arcitles

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{ secrets.GOSSIP_ACCESS_TOKEN }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: AutoSync
        run: python main.py
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GOSSIP_ACCESS_TOKEN }}
