name: sync

on: push
  #schedule:
  #  - cron: '0 21 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{ secrets.GOSSIP_ACCESS_TOKEN }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: AutoSync
        run: python main.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "GoSSIP NewsBot AutoPush"
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GOSSIP_ACCESS_TOKEN }}
